"""Initial schema: system_state, task_executions, comment_logs

Revision ID: 22bba2d16585
Revises:
Create Date: 2025-11-25 22:56:44.725112

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '22bba2d16585'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asana_gid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code_path', sa.Text(), nullable=True),
    sa.Column('portfolio_gid', sa.String(length=50), nullable=False),
    sa.Column('workspace_gid', sa.String(length=50), nullable=False),
    sa.Column('team_gid', sa.String(length=50), nullable=True),
    sa.Column('asana_permalink_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_asana_gid'), 'projects', ['asana_gid'], unique=True)
    op.create_index(op.f('ix_projects_portfolio_gid'), 'projects', ['portfolio_gid'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt_template', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('avg_tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prompts_active', 'prompt_templates', ['agent_type', 'active'], unique=False)
    op.create_index('idx_prompts_unique', 'prompt_templates', ['name', 'agent_type', 'version'], unique=True)
    op.create_table('system_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orchestrator_status', sa.String(length=50), nullable=True),
    sa.Column('orchestrator_pid', sa.Integer(), nullable=True),
    sa.Column('orchestrator_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_portfolio_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_tasks_sync_at', sa.DateTime(), nullable=True),
    sa.Column('total_tasks_processed', sa.Integer(), nullable=True),
    sa.Column('total_tasks_pending', sa.Integer(), nullable=True),
    sa.Column('active_agents_count', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name='singleton_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('resource_gid', sa.String(length=50), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhooks_processed_received', 'webhooks', ['processed', 'received_at'], unique=False)
    op.create_index('idx_webhooks_resource', 'webhooks', ['resource_type', 'resource_gid'], unique=False)
    op.create_index(op.f('ix_webhooks_processed'), 'webhooks', ['processed'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asana_gid', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('html_notes', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('due_on', sa.String(length=50), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('assignee_gid', sa.String(length=50), nullable=True),
    sa.Column('assignee_name', sa.String(length=255), nullable=True),
    sa.Column('assigned_to_aegis', sa.Boolean(), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('num_subtasks', sa.Integer(), nullable=True),
    sa.Column('asana_permalink_url', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_assigned', 'tasks', ['assigned_to_aegis', 'completed'], unique=False)
    op.create_index('idx_tasks_project', 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_asana_gid'), 'tasks', ['asana_gid'], unique=True)
    op.create_index(op.f('ix_tasks_assigned_to_aegis'), 'tasks', ['assigned_to_aegis'], unique=False)
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_task_id', sa.Integer(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('tasks_failed', sa.Integer(), nullable=True),
    sa.Column('total_execution_time_seconds', sa.Integer(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_index(op.f('ix_agents_agent_type'), 'agents', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asana_gid', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_by_gid', sa.String(length=50), nullable=True),
    sa.Column('created_by_name', sa.String(length=255), nullable=True),
    sa.Column('is_from_aegis', sa.Boolean(), nullable=True),
    sa.Column('comment_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_task_created', 'comments', ['task_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_comments_asana_gid'), 'comments', ['asana_gid'], unique=True)
    op.create_table('task_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('execution_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_executions_status', 'task_executions', ['status'], unique=False)
    op.create_index('idx_executions_task', 'task_executions', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_executions_started_at'), 'task_executions', ['started_at'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('task_execution_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_execution_id'], ['task_executions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_agent_occurred', 'agent_events', ['agent_id', 'occurred_at'], unique=False)
    op.create_index('idx_events_execution', 'agent_events', ['task_execution_id'], unique=False)
    op.create_index(op.f('ix_agent_events_event_type'), 'agent_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_events_event_type'), table_name='agent_events')
    op.drop_index('idx_events_execution', table_name='agent_events')
    op.drop_index('idx_events_agent_occurred', table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_task_executions_started_at'), table_name='task_executions')
    op.drop_index('idx_executions_task', table_name='task_executions')
    op.drop_index('idx_executions_status', table_name='task_executions')
    op.drop_table('task_executions')
    op.drop_index(op.f('ix_comments_asana_gid'), table_name='comments')
    op.drop_index('idx_comments_task_created', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_type'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_aegis'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_asana_gid'), table_name='tasks')
    op.drop_index('idx_tasks_project', table_name='tasks')
    op.drop_index('idx_tasks_assigned', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_webhooks_processed'), table_name='webhooks')
    op.drop_index('idx_webhooks_resource', table_name='webhooks')
    op.drop_index('idx_webhooks_processed_received', table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_table('system_state')
    op.drop_index('idx_prompts_unique', table_name='prompt_templates')
    op.drop_index('idx_prompts_active', table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_projects_portfolio_gid'), table_name='projects')
    op.drop_index(op.f('ix_projects_asana_gid'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
